### ISSUE TITLE
Should I run "npm audit fix"?

### ISSUE THREAD

**Issue by Chr0n0AP** [DevonCrawford/Personal-Website#6]
![dc_website](https://user-images.githubusercontent.com/28364472/61655862-66687a00-ac8d-11e9-8f91-819ac890e139.jpg)

Will `npm audit fix` cause any Problems?

**Comment by PineappleIOnic** [comment]
No, npm audit fix shouldn't break anything. If any changes are made which will break something it will notify you and request you to manually review the changes.
